// vue/CODES/vue_ajax/src_2_github搜索案例/components/Search.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input
        type="text"
        placeholder="enter the name you search"
        v-model="keyword"
      />&nbsp;
      <button @click="getSearchResult">Search</button>
    </div>
  </section>
</template>

<script>
export default {
  name: "Search",
  data() {
    return {
      keyword: "",
    };
  },
  methods: {
    getSearchResult() {
      this.$bus.$emit("getSearchResult", this.keyword);
    },
  },
};
</script>

<style>
</style>

// React/CODES/09 脚手架/react-scaffold/20 src_githubSearch/components/Search/index.jsx
import React, { Component } from 'react'
import axios from "axios"

export default class Search extends Component {
  state = { keyword: "" }

  handleChange = (event) => {
    this.setState({ keyword: event.target.value });
  }

  handleClick = () => {
    const { keyword } = this.state;
    const { updateAppState } = this.props;
    updateAppState({ users: [], isFirst: false, isLoading: true, errInfo: "" });
    axios.get(`https://api.github.com/search/users?q=${keyword}`)
      .then(res => {
        updateAppState({ isLoading: false, users: res.data.items });
      })
      .catch(err => {
        updateAppState({ isLoading: false, errInfo: err.message });
      })
  }

  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">Search Github Users</h3>
        <div>
          <input onChange={this.handleChange} type="text" placeholder="enter the name you search" />
          &nbsp;
          <button onClick={this.handleClick}>Search</button>
        </div>
      </section>
    )
  }
}
