// React/CODES/10 路由/react-router/src/App.js
import React, { Component } from 'react'
import {  Route, NavLink } from 'react-router-dom'
import About from "./pages/About"
import Home from "./pages/Home"

export default class App extends Component {
  render() {
    return (
      <div>
        <div className="row">
          <div className="col-xs-offset-2 col-xs-8">
            <div className="page-header"><h2>React Router Demo</h2></div>
          </div>
        </div>
        <div className="row">
          <div className="col-xs-2 col-xs-offset-2">
            <div className="list-group">
              <NavLink className="list-group-item" to="/about" >About</NavLink>
              <NavLink className="list-group-item" to="/home" >Home</NavLink>
            </div>
          </div>
          <div className="col-xs-6">
            <div className="panel">
              <div className="panel-body">
                <Route path="/about" component={About} />
                <Route path="/home" component={Home} />
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

// 7-vue/CODES/vue_router/src/App.vue
<template>
  <div>
    <div class="row">
      <div class="col-xs-offset-2 col-xs-8">
        <div class="page-header">
          <Banner />
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
          <router-link class="list-group-item" active-class="active" to="/home"
            >Home</router-link
          >
          <router-link class="list-group-item" active-class="active" to="/about"
            >About</router-link
          >
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
            <router-view></router-view>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import "../public/css/bootstrap.css";
import Banner from "./components/Banner.vue";
export default {
  name: "App",
  components: { Banner },
};
</script>
